build: false
shallow_clone: false
platform: x86
clone_folder: c:\projects\contaocommunityalliance-composer-plugin

cache:
  - '%LOCALAPPDATA%\Composer\files'

environment:
  COMPOSER_ROOT_VERSION: 2.4.x-dev
  matrix:
    # Keep older versions last so we always have current results first.
    - php_zip: php-7.0.13-Win32-VC14-x86.zip
    - php_zip: php-5.6.28-Win32-VC11-x86.zip
    - php_zip: php-5.5.37-Win32-VC11-x86.zip
    - php_zip: php-5.4.44-Win32-VC9-x86.zip
    - php_zip: php-5.3.29-Win32-VC9-x86.zip

init:
  - SET PATH=c:\php;%PATH%
  - SET SYMFONY_DEPRECATIONS_HELPER=weak

install:
  - mkdir c:\php && cd c:\php
  - ps: appveyor DownloadFile http://windows.php.net/downloads/releases/archives/$env:php_zip
  - ps: 7z x $env:php_zip -y >$null
  - del *.zip
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_bz2.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_exif.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_mysqli.dll >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_pdo_mysql.dll >> php.ini
  - echo extension=php_soap.dll >> php.ini
  - echo extension=php_sockets.dll >> php.ini
  - echo extension=php_xmlrpc.dll >> php.ini
  - echo extension=php_xsl.dll >> php.ini
  - cd c:\projects\contaocommunityalliance-composer-plugin
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar update --no-progress --no-interaction --ansi

test_script:
  - cd c:\projects\contaocommunityalliance-composer-plugin
  - vendor\bin\phpunit.bat
